
# docker run --name api-solid-pg -e POSTGRESQL_USERNAME=dovker -e POSTGRESQL_PASSWORD=docker 
# -e POSTGRESQL_DATABASE=apisolid -p 5432:5432 bitnami/postgresql

services:
  api-solid-pg:
    image: bitnami/postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=dovker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=apisolid
